---
# tasks file for golang-sonarqube-scanner-image
  
# Copyright (C) 2018 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: "create /home/{{ ansible_user_id }}/golang-sonarqube-scanner-image"
  become: yes
  file:
    path: "/home/{{ ansible_user_id }}/golang-sonarqube-scanner-image"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - golang-sonarqube-scanner-image

- name: "template files into /home/{{ ansible_user_id }}/golang-sonarqube-scanner-image"
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"   
  with_items:
    - { src: "templates/Dockerfile.j2", dest: "/home/{{ ansible_user_id }}/golang-sonarqube-scanner-image/Dockerfile" }
    - { src: "templates/dockerfile_build.j2", dest: "/home/{{ ansible_user_id }}/golang-sonarqube-scanner-image/dockerfile_build.sh" }
    - { src: "templates/push_into_private_repo.j2", dest: "/home/{{ ansible_user_id }}/golang-sonarqube-scanner-image/push_into_private_repo.sh" }
  tags:
    - golang-sonarqube-scanner-image

- name: ensure scripts are executable
  become: yes
  file: 
    path: "{{ item.path }}"
    mode: "u=rwx,g=r,o=r"
  with_items:
    - { path: "/home/{{ ansible_user_id }}/golang-sonarqube-scanner-image/dockerfile_build.sh" }
    - { path: "/home/{{ ansible_user_id }}/golang-sonarqube-scanner-image/push_into_private_repo.sh" } 
  tags:
    - golang-sonarqube-scanner-image

- name: build golang-sonarqube-scanner image and push into private registry
  become: yes
  docker_image:
    path: "/home/{{ ansible_user_id }}/golang-sonarqube-scanner-image"
    name: nemonik/golang-sonarqube-scanner
    repository: "{{ hostvars['toolchain']['ansible_host'] }}:5000/nemonik/golang-sonarqube-scanner"
    push: yes
    tag: "{{ sonar_scanner_cli_version }}"
    buildargs:
      http_proxy: "{{ http_proxy|default('') }}"
      HTTP_PROXY: "{{ http_proxy|default('') }}"
      https_proxy: "{{ https_proxy|default('') }}"
      HTTPS_PROXY: "{{ https_proxy|default('') }}"
      NO_PROXY: "{{ no_proxy|default('') }}"
      no_proxy: "{{ no_proxy|default('') }}" 
  tags:
    - golang-sonarqube-scanner-image
  
# - name: build golang-sonarqube-scanner image and push into private registry
#   become: yes
#   shell: |
#     ./dockerfile_build.sh
#     ./push_into_private_repo.sh
#   args:
#     chdir: /home/{{ ansible_user_id }}/golang-sonarqube-scanner-image
#   environment:
#     http_proxy: "{{ http_proxy }}"
#     HTTP_PROXY: "{{ http_proxy }}"
#     https_proxy: "{{ https_proxy }}"
#     HTTPS_PROXY: "{{ https_proxy }}"
#     NO_PROXY: "{{ no_proxy }}"
#     no_proxy: "{{ no_proxy }}" 
#   tags:    
#     - golang-sonarqube-scanner-image
